version: '3.7'

services:
  mongodb:
    image: 'mongo:8'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: payment_flow
    ports:
      - "27017:27017"

  postgres:
    image: postgres:16.3
    volumes:
      - ./payment-flow-challenge.sql:/docker-entrypoint-db.d/payment-flow-challenge.sql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: payment_flow
    ports:
      - "5432:5432"
