spring:
  application:
    name: "payment-flow-challenge"
  kafka:
    bootstrap-servers:
      "PLAINTEXT://localhost:9092"
  r2dbc:
    password: root
    name: payment_flow
    username: root
    url: r2dbc:postgresql://localhost:5432/payment_flow
  data:
    mongodb:
      database: payment_flow
      password: root
      username: root
      host: localhost
  liquibase:
    enabled: true
    change-log: classpath:/config/liquibase/changelog.xml
    url: jdbc:postgresql://localhost:5432/payment_flow
    password: root
    user: root
  webflux:
    problemdetails:
      enabled: true
  web:
    locale: en_US

auth:
  service:
    base-url: https://util.devi.tools/api/v1

kafka:
  topics:
    transfer-notification: transfer-notification

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.web: DEBUG
    org.springframework.validation: DEBUG
    com.payment: DEBUG
