spring:
  application:
    name: "payment-flow-challenge"
  r2dbc:
    password: root
    name: payment_flow
    username: root
    url: r2dbc:postgresql://localhost:5432/payment_flow
  data:
    mongodb:
      database: payment_flow
      password: root
      username: root
      host: localhost
  liquibase:
    enabled: true
    change-log: classpath:/config/liquibase/changelog.xml
    url: jdbc:postgresql://localhost:5432/payment_flow
    password: root
    user: root
  webflux:
    problemdetails:
      enabled: true
  web:
    locale: en_US
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

