spring:
  application:
    name: notification-queue-consumer
  kafka:
    bootstrap-servers:
      "PLAINTEXT://localhost:9092"

notification:
  service:
    base-url: https://util.devi.tools/api/v1
    queue-name: transfer-notification

server:
  port: 8081

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        automatic-transition-from-open-to-half-open-enabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 3
    instances:
      notification-service-A:
        baseConfig: default

  retry:
    instances:
      notification-service-A:
        maxAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
        ##ignoreExceptions:
        ##  - java.io.NotActiveException //just an example

