spring:
  application:
    name: notification-queue-consumer
  kafka:
    bootstrap-servers:
      "PLAINTEXT://localhost:9092"

notification:
  service:
    base-url: https://util.devi.tools/api/v1

server:
  port: 8081

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        minimumNumberOfCalls: 3
        maxWaitDurationInHalfOpenState: 3s
    instances:
      notification-service-A:
        baseConfig: default